/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vultureservices;

import java.awt.event.ActionEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benjamin Edwards
 */
public class EditJob extends javax.swing.JFrame {

    /**
     * Creates new form EditJob
     */
    public EditJob() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) jtbJobs.getModel();
        model.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                String query = "SELECT job_id, job_number FROM job";
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                
                while (rs.next()) {
                    String jobID = rs.getString("job_id");
                    String job = rs.getString("job_number");
                    model.addRow(new Object[]{jobID, job});
                    jtbJobs.setModel(model);
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldMotorID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldClientID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jlbUser = new javax.swing.JLabel();
        jlbWelcome = new javax.swing.JLabel();
        jPanelJob = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jTextFieldJobNo = new javax.swing.JTextField();
        jTextFieldCheckedBy = new javax.swing.JTextField();
        jTextFieldDateCollected = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldCheckedDate = new javax.swing.JTextField();
        jTextFieldInspectedBy = new javax.swing.JTextField();
        jTextFieldApproved = new javax.swing.JTextField();
        jButtonSaveJob = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQuotedParts = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEstimatedTime = new javax.swing.JTextField();
        jTextFieldReturnDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbJobs = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jButtonGo = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldJobID = new javax.swing.JTextField();
        jbtMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonSaveMotor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMotor = new javax.swing.JTextField();
        jTextFieldManufacturer = new javax.swing.JTextField();
        jTextFieldEstDateMan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButtonSaveClient = new javax.swing.JButton();
        jTextFieldClient = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSaveTasks = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbTasks = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldTask = new javax.swing.JTextField();
        jTextFieldNotes = new javax.swing.JTextField();
        jTextFieldTimeNeeded = new javax.swing.JTextField();
        jTextFieldCompleted = new javax.swing.JTextField();
        jTextFieldCompletedDate = new javax.swing.JTextField();
        jTextFieldTimeUsed = new javax.swing.JTextField();

        jTextFieldMotorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotorIDActionPerformed(evt);
            }
        });

        jLabel18.setText("ID:");

        jTextFieldClientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClientIDActionPerformed(evt);
            }
        });

        jLabel17.setText("ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbUser.setText("jLabel1");
        jlbUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jlbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 13, -1, -1));

        jlbWelcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbWelcome.setText("Welcome");
        getContentPane().add(jlbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, -1, -1));

        jLabel1.setText("Job Number:");

        jLabel10.setText("Collected Date:");

        jLabel21.setText("Checked By:");

        jLabel22.setText("Approved:");

        jLabel24.setText("Job Details");

        jLabel25.setText("Completed Date");

        jLabel26.setText("Checked Date:");

        jLabel11.setText("Inspected By:");

        jLabel90.setText("Type date as: YYYY-MM-DD");

        jTextFieldJobNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJobNoActionPerformed(evt);
            }
        });

        jTextFieldCheckedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckedByActionPerformed(evt);
            }
        });

        jTextFieldCheckedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckedDateActionPerformed(evt);
            }
        });

        jButtonSaveJob.setText("Update Jobs");
        jButtonSaveJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveJobActionPerformed(evt);
            }
        });

        jLabel6.setText("Quoted parts needed:");

        jTextFieldQuotedParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuotedPartsActionPerformed(evt);
            }
        });

        jLabel5.setText("Estimated time (H):");

        jTextFieldEstimatedTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstimatedTimeActionPerformed(evt);
            }
        });

        jLabel9.setText("Return Date:");

        javax.swing.GroupLayout jPanelJobLayout = new javax.swing.GroupLayout(jPanelJob);
        jPanelJob.setLayout(jPanelJobLayout);
        jPanelJobLayout.setHorizontalGroup(
            jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobLayout.createSequentialGroup()
                .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel90))
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jButtonSaveJob)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelJobLayout.createSequentialGroup()
                .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addContainerGap(78, Short.MAX_VALUE)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInspectedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelJobLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJobLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstimatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanelJobLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCheckedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDateCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCheckedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQuotedParts, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJobLayout.setVerticalGroup(
            jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobLayout.createSequentialGroup()
                .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldJobNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDateCollected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldInspectedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldApproved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextFieldCheckedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldEstimatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanelJobLayout.createSequentialGroup()
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCheckedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldQuotedParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButtonSaveJob)
                .addContainerGap())
        );

        getContentPane().add(jPanelJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 18, 861, -1));

        jtbJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job ID", "Job"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbJobs.setRequestFocusEnabled(false);
        jtbJobs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbJobsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbJobs);

        jLabel23.setText("Select the job ID to edit:");

        jButtonGo.setText("Go");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jLabel31.setText("Select Job");

        jTextFieldJobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJobIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel31))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldJobID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jButtonGo)
                            .addComponent(jTextFieldJobID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(336, 336, 336))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, -1, 212));

        jbtMenu.setText("Finish and Close");
        jbtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jbtMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 790, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSaveMotor.setText("Update Motor");
        jButtonSaveMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveMotorActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSaveMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel2.setText("Motor:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setText("Manufacturer:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel4.setText("Motor Details");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jTextFieldMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotorActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 241, -1));

        jTextFieldManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManufacturerActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 241, -1));
        jPanel2.add(jTextFieldEstDateMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 238, -1));

        jLabel27.setText("Estimated Date of Manufacture:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 267, 963, -1));

        jLabel7.setText("Client:");

        jButtonSaveClient.setText("Update Clients");
        jButtonSaveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveClientActionPerformed(evt);
            }
        });

        jTextFieldClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClientActionPerformed(evt);
            }
        });

        jLabel12.setText("Client Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClient)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonSaveClient)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(163, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(154, 154, 154)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSaveClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel12)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 267, -1, -1));

        jButtonSaveTasks.setText("Update Tasks");
        jButtonSaveTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveTasksActionPerformed(evt);
            }
        });

        jtbTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task ID", "Task", "notes", "Time Needed", "Completed", "Completed Date", "Time used"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTasks.setRequestFocusEnabled(false);
        jtbTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTasksMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbTasks);

        jLabel20.setText("Select A field to edit");

        jLabel3.setText("Change Task to:");

        jLabel13.setText("Change Notes to:");

        jLabel14.setText("Change Time Needed to:");

        jLabel15.setText("Change Completed to:");

        jLabel16.setText("Change Completed Date to:");

        jLabel28.setText("Change Time used to:");

        jTextFieldTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaskActionPerformed(evt);
            }
        });

        jTextFieldNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotesActionPerformed(evt);
            }
        });

        jTextFieldTimeNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeNeededActionPerformed(evt);
            }
        });

        jTextFieldCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCompletedActionPerformed(evt);
            }
        });

        jTextFieldCompletedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCompletedDateActionPerformed(evt);
            }
        });

        jTextFieldTimeUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeUsedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel3)
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCompletedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel14)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel15)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldTimeUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jTextFieldTask, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextFieldNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTimeNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSaveTasks)
                .addGap(629, 629, 629))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTimeNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompletedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTimeUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButtonSaveTasks)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 419, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldJobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJobIDActionPerformed

    private void jTextFieldClientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClientIDActionPerformed

    private void jTextFieldClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClientActionPerformed

    private void jButtonSaveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveClientActionPerformed

        jButtonSaveClientsActionPerformed(evt);

    }//GEN-LAST:event_jButtonSaveClientActionPerformed

    private void jButtonSaveMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveMotorActionPerformed

        jButtonSaveMotorsActionPerformed(evt);
    }//GEN-LAST:event_jButtonSaveMotorActionPerformed

    private void jTextFieldManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManufacturerActionPerformed

    private void jTextFieldMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotorActionPerformed

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed

        String selection1 = jTextFieldJobID.getText();
        String query1 = "SELECT * FROM job WHERE job_id = " + selection1;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                PreparedStatement ps1 = con.prepareStatement(query1);
                ResultSet rs1 = ps1.executeQuery();
                while (rs1.next()) {
                    jTextFieldJobNo.setText(rs1.getString("job_number"));
                    jTextFieldDateCollected.setText(rs1.getString("date_collected"));
                    jTextFieldReturnDate.setText(rs1.getString("return_date"));
                    jTextFieldEstimatedTime.setText(rs1.getString("labour_time"));
                    jTextFieldCheckedBy.setText(rs1.getString("checked_by"));
                    jTextFieldCheckedDate.setText(rs1.getString("checkedby_date"));
                    jTextFieldApproved.setText(rs1.getString("approved"));
                    jTextFieldInspectedBy.setText(rs1.getString("inspected_by"));
                    jTextFieldDate.setText(rs1.getString("completed_date"));
                    jTextFieldQuotedParts.setText(rs1.getString("parts_needed"));
                    jTextFieldMotorID.setText(rs1.getString("motor_id")); 
                }
                
                String selection2 = jTextFieldMotorID.getText();
                String query2 = "SELECT * FROM motor WHERE motor_id = " + selection2;
                try
                {
                    PreparedStatement ps2 = con.prepareStatement(query2);
                    ResultSet rs2 = ps2.executeQuery();
                    while (rs2.next()) {
                        jTextFieldMotor.setText(rs2.getString("motor"));
                        jTextFieldManufacturer.setText(rs2.getString("manufacturer"));
                        jTextFieldEstDateMan.setText(rs2.getString("estimated_date_of_manufacture"));
                        jTextFieldClientID.setText(rs2.getString("client_id"));
                    }
                    
                    String selection3 = jTextFieldClientID.getText();
                    String query3 = "SELECT * FROM client WHERE client_id = " + selection3;
                    try
                    {
                        PreparedStatement ps3 = con.prepareStatement(query3);
                        ResultSet rs3 = ps3.executeQuery();
                        while (rs3.next()) {
                            jTextFieldClient.setText(rs3.getString("client_name"));
                        }
                      
                        DefaultTableModel model = (DefaultTableModel) jtbTasks.getModel();
                        model.setRowCount(0);
                        try{
                            String query = "SELECT task_id, task, notes, time_needed, completed, date_completed, time_used FROM task WHERE job_id=" + jTextFieldJobID.getText();
                            PreparedStatement ps = con.prepareStatement(query);
                            ResultSet rs = ps.executeQuery();
                
                            while (rs.next()) {
                                String TaskID = rs.getString("task_id");
                                String Task = rs.getString("task");
                                String Notes = rs.getString("notes");
                                String TimeNeeded = rs.getString("time_needed");
                                String Completed = rs.getString("completed");
                                String DateCompleted = rs.getString("date_completed");
                                String TimeUsed = rs.getString("time_used");
                                model.addRow(new Object[]{TaskID, Task, Notes, TimeNeeded, Completed, DateCompleted, TimeUsed});
                                jtbTasks.setModel(model);
                            } 
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
            }
                        
                    } catch (Exception e) {
                    System.out.println(e);
                }
                    
                } catch (Exception e) {
                    System.out.println(e);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jtbJobsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbJobsMouseClicked

    }//GEN-LAST:event_jtbJobsMouseClicked

    private void jTextFieldMotorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotorIDActionPerformed

    private void jTextFieldQuotedPartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuotedPartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuotedPartsActionPerformed

    private void jTextFieldJobNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJobNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJobNoActionPerformed

    private void jTextFieldEstimatedTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstimatedTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstimatedTimeActionPerformed

    private void jTextFieldCheckedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckedByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckedByActionPerformed

    private void jTextFieldCheckedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckedDateActionPerformed

    private void jbtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMenuActionPerformed

        String user = jlbUser.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                String query = "SELECT * FROM employees WHERE emp_name =?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, user);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String role = rs.getString("emp_role");
                    dispose();

                    if (role.equals("Technician")) {
                        TechnicianHome tf = new TechnicianHome();
                        tf.setVisible(true);
                        tf.setSize(800, 600);
                        tf.setLocationRelativeTo(null);
                        tf.jlbUser.setText(user);
                    }

                    if (role.equals("Customer Services")) {
                        CSHome cf = new CSHome();
                        cf.setVisible(true);
                        cf.setSize(800, 600);
                        cf.setLocationRelativeTo(null);
                        cf.jlbUser.setText(user);
                    }

                    if (role.equals("Finance")) {
                        FinanceHome ff = new FinanceHome();
                        ff.setVisible(true);
                        ff.setSize(800, 600);
                        ff.setLocationRelativeTo(null);
                        ff.jlbUser.setText(user);
                    }

                    if (role.equals("Human Resources")) {
                        CSHome hf = new CSHome();
                        hf.setVisible(true);
                        hf.setSize(800, 600);
                        hf.setLocationRelativeTo(null);
                        hf.jlbUser.setText(user);
                    }
                    if (role.equals("Manager") || role.equals("IT Services")) {
                        ManagerHome mf = new ManagerHome();
                        mf.setVisible(true);
                        mf.setSize(800, 600);
                        mf.setLocationRelativeTo(null);
                        mf.jlbUser.setText(user);
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jbtMenuActionPerformed

    private void jButtonSaveJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveJobActionPerformed

        jButtonSaveJobsActionPerformed(evt);
        
    }//GEN-LAST:event_jButtonSaveJobActionPerformed

    private void jButtonSaveTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveTasksActionPerformed

        String Task = jTextFieldTask.getText();
        String Notes = jTextFieldNotes.getText();
        String TimeNeeded = jTextFieldTimeNeeded.getText();
        String Completed = jTextFieldCompleted.getText();
        String CompletedDate = jTextFieldCompletedDate.getText();
        String TimeUsed = jTextFieldTimeUsed.getText();
        
        if (Task.equals("") || Notes.equals("") || TimeNeeded.equals("") || Completed.equals("") || CompletedDate.equals("") || TimeUsed.equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Make sure all fields are filled in");
        } else {
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                    String query = "UPDATE task SET task=?, notes=?, time_needed=?, completed=?, date_completed=?, time_used=? WHERE task_id=?";
                    PreparedStatement ps = con.prepareStatement(query);
                    int row = jtbTasks.getSelectedRow();
                    String cell = jtbTasks.getModel().getValueAt(row, 0).toString();
                    ps.setString(7, cell);
                    ps.setString(1, Task);
                    ps.setString(2, Notes);
                    ps.setString(3, TimeNeeded);
                    ps.setString(4, Completed);
                    ps.setString(5, CompletedDate);
                    ps.setString(6, TimeUsed);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Tasks updated successfully.");
                    updateTable();
                    
            } catch (Exception e) {
                System.out.println(e);
            }
                    
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButtonSaveTasksActionPerformed

    private void jtbTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTasksMouseClicked

        int row = jtbTasks.getSelectedRow();
        String selection = jtbTasks.getModel().getValueAt(row, 0).toString();
        String query = "SELECT * FROM task WHERE task_id = " + selection;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    jTextFieldTask.setText(rs.getString("task"));
                    jTextFieldNotes.setText(rs.getString("notes"));
                    jTextFieldTimeNeeded.setText(rs.getString("time_needed"));
                    jTextFieldCompleted.setText(rs.getString("completed"));
                    jTextFieldCompletedDate.setText(rs.getString("date_completed"));
                    jTextFieldTimeUsed.setText(rs.getString("time_used"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtbTasksMouseClicked

    private void jTextFieldTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskActionPerformed

    private void jTextFieldNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotesActionPerformed

    private void jTextFieldTimeNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeNeededActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeNeededActionPerformed

    private void jTextFieldCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompletedActionPerformed

    private void jTextFieldCompletedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCompletedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCompletedDateActionPerformed

    private void jTextFieldTimeUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeUsedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeUsedActionPerformed

    public void jButtonSaveClientsActionPerformed(java.awt.event.ActionEvent evt) {                                                  

        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066"))
            {
                String query = ("UPDATE client SET client_name = ? WHERE client_id =" + jTextFieldClientID.getText());
                PreparedStatement pst = con.prepareStatement(query);
                
                pst.setString(1, jTextFieldClient.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Client Data saved");
                
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void jButtonSaveMotorsActionPerformed(java.awt.event.ActionEvent evt) {                                                 

        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066"))
            {
                String query = ("UPDATE motor SET motor = ?, manufacturer = ?, estimated_date_of_manufacture = ?, client_id = ? WHERE motor_id =" + jTextFieldMotorID.getText());
                PreparedStatement pst = con.prepareStatement(query);
                
                pst.setString(1, jTextFieldMotor.getText());
                pst.setString(2, jTextFieldManufacturer.getText());
                pst.setString(3, jTextFieldEstDateMan.getText());
                pst.setString(4, jTextFieldClientID.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Motor Data saved");
                
                }
        
        } catch (Exception e) {
            System.out.println(e);
        }          
    }
    
    public void jButtonSaveJobsActionPerformed(java.awt.event.ActionEvent evt) {                                               

        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066"))
            {
                String query = ("UPDATE job SET job_number = ?, date_collected = ?, return_date = ?, labour_time = ?, checked_by = ?, checkedby_date = ?, approved = ?, inspected_by = ?, completed_date = ?, parts_needed = ?, motor_id = ? WHERE job_id =" + jTextFieldJobID.getText());
                PreparedStatement pst = con.prepareStatement(query);

                pst.setString(1, jTextFieldJobNo.getText());
                pst.setString(2, jTextFieldDateCollected.getText());
                pst.setString(3, jTextFieldReturnDate.getText());
                pst.setString(4, jTextFieldEstimatedTime.getText());
                pst.setString(5, jTextFieldCheckedBy.getText());
                pst.setString(6, jTextFieldCheckedDate.getText());
                pst.setString(7, jTextFieldApproved.getText());
                pst.setString(8, jTextFieldInspectedBy.getText());
                pst.setString(9, jTextFieldDate.getText());
                pst.setString(10, jTextFieldQuotedParts.getText());
                pst.setString(11, jTextFieldMotorID.getText());
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Job Data saved");
                
                }
        
        } catch (Exception e) {
            System.out.println(e);
        } 
    }
    
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) jtbTasks.getModel();
        model.setRowCount(0);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vulture", "root", "24652066")) {
                String query = "SELECT * FROM task  WHERE job_id=" + jTextFieldJobID.getText();
                PreparedStatement ps = con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    String TaskID = rs.getString("task_id");
                    String Task = rs.getString("task");
                    String Notes = rs.getString("notes");
                    String TimeNeeded = rs.getString("time_needed");
                    String Completed = rs.getString("completed");
                    String DateCompleted = rs.getString("date_completed");
                    String TimeUsed = rs.getString("time_used");
                    model.addRow(new Object[]{TaskID, Task, Notes, TimeNeeded, Completed, DateCompleted, TimeUsed});
                    jtbTasks.setModel(model);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonSaveClient;
    private javax.swing.JButton jButtonSaveJob;
    private javax.swing.JButton jButtonSaveMotor;
    private javax.swing.JButton jButtonSaveTasks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelJob;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldApproved;
    private javax.swing.JTextField jTextFieldCheckedBy;
    private javax.swing.JTextField jTextFieldCheckedDate;
    private javax.swing.JTextField jTextFieldClient;
    private javax.swing.JTextField jTextFieldClientID;
    private javax.swing.JTextField jTextFieldCompleted;
    private javax.swing.JTextField jTextFieldCompletedDate;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDateCollected;
    private javax.swing.JTextField jTextFieldEstDateMan;
    private javax.swing.JTextField jTextFieldEstimatedTime;
    private javax.swing.JTextField jTextFieldInspectedBy;
    private javax.swing.JTextField jTextFieldJobID;
    private javax.swing.JTextField jTextFieldJobNo;
    private javax.swing.JTextField jTextFieldManufacturer;
    private javax.swing.JTextField jTextFieldMotor;
    private javax.swing.JTextField jTextFieldMotorID;
    private javax.swing.JTextField jTextFieldNotes;
    private javax.swing.JTextField jTextFieldQuotedParts;
    private javax.swing.JTextField jTextFieldReturnDate;
    private javax.swing.JTextField jTextFieldTask;
    private javax.swing.JTextField jTextFieldTimeNeeded;
    private javax.swing.JTextField jTextFieldTimeUsed;
    private javax.swing.JButton jbtMenu;
    public javax.swing.JLabel jlbUser;
    public javax.swing.JLabel jlbWelcome;
    private javax.swing.JTable jtbJobs;
    private javax.swing.JTable jtbTasks;
    // End of variables declaration//GEN-END:variables
}
